/**
 * gen-web-assets.ts —— 把 src/gateway/web/ 前端资源打包成 base64 资源表
 * （src/gateway/web-assets.generated.ts），供 localGateway.ts 内嵌 serve。
 *
 * 由构建脚本 build.ts 在每次构建前自动运行；也可单独执行：
 *   bun run ./scripts/gen-web-assets.ts
 *
 * 前端改动流程（写入 CLAUDE.md 开发工作流）：
 *   改 src/gateway/web/ → 重新构建（build:dev:gateway）→ exe 内自动带上最新前端。
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const webDir = join(import.meta.dir, '..', 'src', 'gateway', 'web')
const outFile = join(import.meta.dir, '..', 'src', 'gateway', 'web-assets.generated.ts')

const names: string[] = []
// 递归收集 webDir 下所有文件（含子目录，如 char/1.jpg），key 用相对 webDir 的正斜杠路径，
// 与 localGateway.ts 静态路由的 url.pathname 前缀一致（index.html 顶层特判为 '/'）。
function collect(dir: string, base: string): void {
  for (const f of readdirSync(dir)) {
    if (f.startsWith('.')) continue
    const full = join(dir, f)
    const rel = base ? `${base}/${f}` : f
    try {
      if (statSync(full).isFile()) names.push(rel)
      else if (statSync(full).isDirectory()) collect(full, rel)
    } catch {
      /* 忽略单个 */
    }
  }
}
if (existsSync(webDir)) collect(webDir, '')
names.sort()

let out = '// AUTO-GENERATED by scripts/gen-web-assets.ts — 勿手改；改动 src/gateway/web/ 后重新构建自动再生成。\n'
out += 'export const webAssets: Record<string, string> = {\n'
for (const f of names) {
  const b64 = readFileSync(join(webDir, f)).toString('base64')
  out += `  ${JSON.stringify(f)}: ${JSON.stringify(b64)},\n`
}
out += '}\n'
writeFileSync(outFile, out)
console.log(`[gen-web-assets] ${names.length} 个前端资源 → ${outFile}`)
